import bcryptjs from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Afiq Sam',
      email: 'afiqsamadmin@samshop.com',
      password: bcryptjs.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Alin Comel',
      email: 'Alinadmin@samshop.com',
      password: bcryptjs.hashSync('123456'),
      isAdmin: true,
    },
  ],

  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpeg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Designed with small intricate scallop embroidery that is perfect for days when you want to inject a classic element into your wardrobe. This shawl is made from textured chiffon, a wonderful twist from the basic chiffon material. Fully embroidered on all 4 sides of the shawl, Saleha Embroidered Shawl adds an elegant classic touch to the wearer. - Material: Textured chiffon',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description:
        'Designed with small intricate scallop embroidery that is perfect for days when you want to inject a classic element into your wardrobe. This shawl is made from textured chiffon, a wonderful twist from the basic chiffon material. Fully embroidered on all 4 sides of the shawl, Saleha Embroidered Shawl adds an elegant classic touch to the wearer. - Material: Textured chiffon',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description:
        'Designed with small intricate scallop embroidery that is perfect for days when you want to inject a classic element into your wardrobe. This shawl is made from textured chiffon, a wonderful twist from the basic chiffon material. Fully embroidered on all 4 sides of the shawl, Saleha Embroidered Shawl adds an elegant classic touch to the wearer. - Material: Textured chiffon',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description:
        'Designed with small intricate scallop embroidery that is perfect for days when you want to inject a classic element into your wardrobe. This shawl is made from textured chiffon, a wonderful twist from the basic chiffon material. Fully embroidered on all 4 sides of the shawl, Saleha Embroidered Shawl adds an elegant classic touch to the wearer. - Material: Textured chiffon',
    },
  ],
  MalaysiaState: [
    {
      administrative_division: 'State of Malaysia',
      state: 'Johor',
      capital: 'Johor Bahru',

      population: 3794000,
      total_area: 19166,
      licence_plate_prefix: 'J',
      phone_area_code: '07, 06 (Muar & Tangkak)',
      abbreviation: 'JHR',
      ISO: 'MY-01',
      FIPS: 'MY01',
      HDI: 0.818,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Kedah',
      capital: 'Alor Setar',

      population: 2194100,
      total_area: 9492,
      licence_plate_prefix: 'K',
      phone_area_code: '04',
      abbreviation: 'KDH',
      ISO: 'MY-02',
      FIPS: 'MY03',
      HDI: 0.802,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Kelantan',
      capital: 'Kota Bharu',

      population: 1928800,
      total_area: 15040,
      licence_plate_prefix: 'D',
      phone_area_code: '09',
      abbreviation: 'KTN',
      ISO: 'MY-03',
      FIPS: 'MY03',
      HDI: 0.772,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Malacca',
      capital: 'Malacca City',

      population: 937500,
      total_area: 1712,
      licence_plate_prefix: 'M',
      phone_area_code: '06',
      abbreviation: 'MLK',
      ISO: 'MY-04',
      FIPS: 'MY04',
      HDI: 0.828,
      region: 'Peninsular Malaysia',
      head_of_state: 'Yang di-Pertua Negeri (Governor)',
      head_of_goverment: 'Chief Minister',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Negeri Sembilan',
      capital: 'Seremban',

      population: 1129100,
      total_area: 6658,
      licence_plate_prefix: 'N',
      phone_area_code: '06',
      abbreviation: 'NSN',
      ISO: 'MY-05',
      FIPS: 'MY05',
      HDI: 0.822,
      region: 'Peninsular Malaysia',
      head_of_state: 'Yang di-Pertua Negeri (Grand Ruler)',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Pahang',
      capital: 'Kuantan',

      population: 1684600,
      total_area: 35965,
      licence_plate_prefix: 'C',
      phone_area_code: '09, 03 (Genting Highlands), 05 (Cameron)',
      abbreviation: 'PHG',
      ISO: 'MY-06',
      FIPS: 'MY06',
      HDI: 0.797,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Penang',
      capital: 'George Town',

      population: 1774400,
      total_area: 1049,
      licence_plate_prefix: 'P',
      phone_area_code: '04',
      abbreviation: 'PNG',
      ISO: 'MY-07',
      FIPS: 'MY09',
      HDI: 0.838,
      region: 'Peninsular Malaysia',
      head_of_state: 'Yang di-Pertua Negeri (Governor)',
      head_of_goverment: 'Chief Minister',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Perak',
      capital: 'Ipoh',

      population: 2508900,
      total_area: 21146,
      licence_plate_prefix: 'A',
      phone_area_code: '05',
      abbreviation: 'PRK',
      ISO: 'MY-08',
      FIPS: 'MY07',
      HDI: 0.809,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Perlis',
      capital: 'Kangar',

      population: 255400,
      total_area: 819,
      licence_plate_prefix: 'R',
      phone_area_code: '04',
      abbreviation: 'PLS',
      ISO: 'MY-09',
      FIPS: 'MY08',
      HDI: 0.799,
      region: 'Peninsular Malaysia',
      head_of_state: 'Raja',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Sabah',
      capital: 'Kota Kinabalu',

      population: 3833000,
      total_area: 73621,
      licence_plate_prefix: 'S',
      phone_area_code: '087–089',
      abbreviation: 'SBH',
      ISO: 'MY-12',
      FIPS: 'MY16',
      HDI: 0.704,
      region: 'East Malaysia',
      head_of_state: 'Yang di-Pertua Negeri (Governor)',
      head_of_goverment: 'Chief Minister',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Sarawak',
      capital: 'Kuching',

      population: 2822200,
      total_area: 124450,
      licence_plate_prefix: 'Q',
      phone_area_code: '081–086',
      abbreviation: 'SWK',
      ISO: 'MY-13',
      FIPS: 'MY11',
      HDI: 0.739,
      region: 'East Malaysia',
      head_of_state: 'Yang di-Pertua Negeri (Governor)',
      head_of_goverment: 'Chief Minister',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Selangor',
      capital: 'Shah Alam',

      population: 6555400,
      total_area: 7951,
      licence_plate_prefix: 'B',
      phone_area_code: '03',
      abbreviation: 'SGR',
      ISO: 'MY-10',
      FIPS: 'MY12',
      HDI: 0.855,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'State of Malaysia',
      state: 'Terengganu',
      capital: 'Kuala Terengganu',

      population: 1275100,
      total_area: 12958,
      licence_plate_prefix: 'T',
      phone_area_code: '09',
      abbreviation: 'TRG',
      ISO: 'MY-11',
      FIPS: 'MY13',
      HDI: 0.793,
      region: 'Peninsular Malaysia',
      head_of_state: 'Sultan',
      head_of_goverment: 'Menteri Besar',
    },
    {
      administrative_division: 'Federal Territory of Malaysia',
      state: 'Kuala Lumpur',
      capital: 'Kuala Lumpur',

      population: 1746600,
      total_area: 243,
      licence_plate_prefix: 'W / V',
      phone_area_code: '03',
      abbreviation: 'KUL',
      ISO: 'MY-14',
      FIPS: '',
      HDI: 0.86,
      region: 'Peninsular Malaysia',
      head_of_state: 'Yang di-Pertuan Agong',
      head_of_goverment: 'Mayor',
    },
    {
      administrative_division: 'Federal Territory of Malaysia',
      state: 'Labuan',
      capital: 'Victoria',

      population: 100100,
      total_area: 92,
      licence_plate_prefix: 'L',
      phone_area_code: '087',
      abbreviation: 'LBN',
      ISO: 'MY-15',
      FIPS: 'MY15',
      HDI: 0.778,
      region: 'East Malaysia',
      head_of_state: 'Yang di-Pertuan Agong',
      head_of_goverment: 'President of Labuan Corporation',
    },
    {
      administrative_division: 'Federal Territory of Malaysia',
      state: 'Putrajaya',
      capital: 'Putrajaya',

      population: 116100,
      total_area: 49,
      licence_plate_prefix: 'F',
      phone_area_code: '03',
      abbreviation: 'PJY',
      ISO: 'MY-16',
      FIPS: '',
      HDI: 0.877,
      region: 'Peninsular Malaysia',
      head_of_state: 'Yang di-Pertuan Agong',
      head_of_goverment: 'President of Putrajaya Corporation',
    },
  ],
};
export default data;
